import React, { useState } from "react";
import { X, Code, Copy, Check, Download, FileCode, FileJson } from "lucide-react";

// Generate Python code from workflow
const generatePythonCode = (nodes, edges, workflowName) => {
    const nodeList = Object.values(nodes);

    return `"""
${workflowName} - Auto-generated by Nexus
Autonomous workflow for x402-powered trading
"""

import requests
import json
from web3 import Web3

# Configuration
TREASURY_CONTRACT = "0x..."  # Deploy and update
RPC_URL = "https://testnet.zkevm.cronos.org"
PRIVATE_KEY = "YOUR_PRIVATE_KEY"

w3 = Web3(Web3.HTTPProvider(RPC_URL))

class NexusWorkflow:
    def __init__(self):
        self.nodes = ${JSON.stringify(nodeList.map(n => ({ type: n.data?.type, label: n.data?.label, config: n.data?.node_data })), null, 8).replace(/"/g, "'")}
        
    def execute_node(self, node):
        """Execute a single workflow node"""
        node_type = node.get('type')
        config = node.get('config', {})
        
        if node_type == 'pyth-network':
            return self.fetch_price(config.get('symbol', 'ETH_USD'))
        elif node_type == 'condition':
            return self.evaluate_condition(config.get('condition'))
        elif node_type == 'swap':
            return self.execute_swap(config)
        elif node_type == 'nexusPay':
            return self.handle_402_payment(config)
        else:
            print(f"Unknown node type: {node_type}")
            return None
    
    def fetch_price(self, symbol):
        """Fetch price from Pyth oracle"""
        # Mock implementation - replace with real Pyth
        prices = {'ETH_USD': 3500, 'BTC_USD': 98000, 'CRO_USD': 0.15}
        return prices.get(symbol, 0)
    
    def evaluate_condition(self, condition):
        """Evaluate a condition string"""
        # Simple condition parser
        return True  # Implement based on your logic
    
    def execute_swap(self, config):
        """Execute token swap via 1inch or similar"""
        print(f"Executing swap: {config}")
        return True
    
    def handle_402_payment(self, config):
        """Handle x402 payment flow"""
        api_url = config.get('api_url', '')
        
        # Step 1: Make request, expect 402
        response = requests.get(api_url)
        
        if response.status_code == 402:
            # Step 2: Parse payment requirements
            payment_info = response.headers.get('X-Payment-Required')
            
            # Step 3: Sign and submit payment
            # ... Web3 transaction logic
            
            # Step 4: Retry with payment proof
            print("Payment submitted, retrying request...")
            
        return response.json()
    
    def run(self):
        """Execute the full workflow"""
        print(f"Starting workflow: ${workflowName}")
        
        for i, node in enumerate(self.nodes):
            print(f"Executing node {i+1}: {node.get('label')}")
            result = self.execute_node(node)
            print(f"Result: {result}")
        
        print("Workflow complete!")

if __name__ == "__main__":
    workflow = NexusWorkflow()
    workflow.run()
`;
};

// Generate JavaScript code from workflow
const generateJavaScriptCode = (nodes, edges, workflowName) => {
    const nodeList = Object.values(nodes);

    return `/**
 * ${workflowName} - Auto-generated by Nexus
 * Autonomous workflow for x402-powered trading
 */

const { ethers } = require('ethers');

// Configuration
const CONFIG = {
  rpcUrl: 'https://testnet.zkevm.cronos.org',
  treasuryContract: '0x...', // Deploy and update
  privateKey: process.env.PRIVATE_KEY,
};

const nodes = ${JSON.stringify(nodeList.map(n => ({ type: n.data?.type, label: n.data?.label, config: n.data?.node_data })), null, 2)};

// Node executors
const executors = {
  'pyth-network': async (config) => {
    const prices = { 'ETH_USD': 3500, 'BTC_USD': 98000, 'CRO_USD': 0.15 };
    return prices[config.symbol] || 0;
  },
  
  'condition': async (config, context) => {
    // Evaluate condition against context
    return true; // Implement your logic
  },
  
  'swap': async (config) => {
    console.log('Executing swap:', config);
    return { success: true };
  },
  
  'nexusPay': async (config) => {
    const response = await fetch(config.api_url);
    
    if (response.status === 402) {
      const paymentRequired = response.headers.get('X-Payment-Required');
      console.log('Payment required:', paymentRequired);
      
      // Sign and submit payment using ethers.js
      const provider = new ethers.JsonRpcProvider(CONFIG.rpcUrl);
      const wallet = new ethers.Wallet(CONFIG.privateKey, provider);
      
      // ... payment transaction logic
    }
    
    return await response.json();
  },
};

async function runWorkflow() {
  console.log('Starting workflow: ${workflowName}');
  
  const context = {};
  
  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i];
    console.log(\`Executing node \${i + 1}: \${node.label}\`);
    
    const executor = executors[node.type];
    if (executor) {
      context[node.label] = await executor(node.config, context);
      console.log('Result:', context[node.label]);
    } else {
      console.log('Unknown node type:', node.type);
    }
  }
  
  console.log('Workflow complete!');
  return context;
}

runWorkflow().catch(console.error);
`;
};

export default function ExportPanel({ isOpen, onClose, nodes, edges, workflowName }) {
    const [exportType, setExportType] = useState("python");
    const [copied, setCopied] = useState(false);

    if (!isOpen) return null;

    const nodeData = {};
    nodes.forEach(n => { nodeData[n.id] = n; });

    const code = exportType === "python"
        ? generatePythonCode(nodeData, edges, workflowName || "Untitled Workflow")
        : generateJavaScriptCode(nodeData, edges, workflowName || "Untitled Workflow");

    const handleCopy = () => {
        navigator.clipboard.writeText(code);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const ext = exportType === "python" ? "py" : "js";
        const blob = new Blob([code], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${(workflowName || "workflow").toLowerCase().replace(/\s+/g, "_")}.${ext}`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <>
            <div
                className={`fixed inset-0 bg-black/30 z-40 transition-opacity duration-300 ${isOpen ? "opacity-100" : "opacity-0 pointer-events-none"}`}
                onClick={onClose}
            />

            <div className={`fixed top-0 right-0 h-full w-[600px] bg-white shadow-2xl z-50 transform transition-transform duration-300 ease-out ${isOpen ? "translate-x-0" : "translate-x-full"} flex flex-col`}>
                {/* Header */}
                <div className="px-5 py-4 border-b border-slate-200 flex items-center justify-between flex-shrink-0">
                    <div className="flex items-center gap-3">
                        <Code size={20} className="text-slate-600" />
                        <div>
                            <h2 className="font-semibold text-slate-800">Export Workflow</h2>
                            <p className="text-xs text-slate-500">Generate executable code</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-slate-100 rounded-lg text-slate-500">
                        <X size={18} />
                    </button>
                </div>

                {/* Language Selector */}
                <div className="px-5 py-3 border-b border-slate-100 flex gap-2">
                    <button
                        onClick={() => setExportType("python")}
                        className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${exportType === "python" ? "bg-slate-800 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                            }`}
                    >
                        <FileCode size={16} />
                        Python
                    </button>
                    <button
                        onClick={() => setExportType("javascript")}
                        className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${exportType === "javascript" ? "bg-slate-800 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                            }`}
                    >
                        <FileJson size={16} />
                        JavaScript
                    </button>
                </div>

                {/* Code Preview */}
                <div className="flex-1 overflow-hidden flex flex-col">
                    <div className="px-5 py-2 flex items-center justify-between bg-slate-50 border-b border-slate-200">
                        <span className="text-xs text-slate-500 font-mono">
                            {workflowName || "workflow"}.{exportType === "python" ? "py" : "js"}
                        </span>
                        <div className="flex gap-2">
                            <button
                                onClick={handleCopy}
                                className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium text-slate-600 hover:text-slate-800 hover:bg-slate-200 rounded transition-all"
                            >
                                {copied ? <Check size={14} className="text-green-600" /> : <Copy size={14} />}
                                {copied ? "Copied!" : "Copy"}
                            </button>
                            <button
                                onClick={handleDownload}
                                className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium bg-slate-800 text-white rounded hover:bg-slate-700 transition-all"
                            >
                                <Download size={14} />
                                Download
                            </button>
                        </div>
                    </div>
                    <pre className="flex-1 overflow-auto p-4 bg-slate-900 text-slate-300 text-xs font-mono leading-relaxed">
                        {code}
                    </pre>
                </div>

                {/* Footer */}
                <div className="px-5 py-4 border-t border-slate-200 bg-slate-50">
                    <p className="text-xs text-slate-500">
                        Generated code requires configuration. Update contract addresses and API keys before running.
                    </p>
                </div>
            </div>
        </>
    );
}
